### ISSUE TITLE
inference checkpoint

### ISSUE THREAD

**Issue by xuehua-desu** [zeyuwang-zju/UP-Diff#4]
I apologize for bothering you again. During the inference process, your code shows that the weight information does not match, with differences in the names of the key-value pairs. This cannot be achieved solely through the conversion weight method you provided, and I would appreciate it if you could help me with this issue. Thank you.

**Comment by xuehua-desu** [comment]
The problem has been resolved, thank you.

**Comment by zeyuwang-zju** [comment]
Sorry for the late reply. Could you tell me what is the bug and how to resolve it? I will revise the bug.
